package org.example.sijalsystem.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.example.sijalsystem.API.APIException;
import org.example.sijalsystem.Model.InterviewSession;
import org.example.sijalsystem.Model.InterviewAnalysisByAi; // عدّل الاسم لو مختلف
import org.example.sijalsystem.Repository.InterviewSessionRepository;
import org.example.sijalsystem.Repository.InterviewAnalysisByAiRepository;
import org.springframework.stereotype.Service;

import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

@Service
@RequiredArgsConstructor
public class InterviewAnalysisByAiService {

    private final InterviewSessionRepository sessionRepo;
    private final InterviewAnalysisByAiRepository analysisRepo;
    private final OpenAiService openAiService;

    private final ObjectMapper mapper = new ObjectMapper();

    // ================== PUBLIC API ==================

    @Transactional
    public void analyzeAndSave(Integer sessionId, String transcript) {

        InterviewSession session = sessionRepo.findInterviewSessionById(sessionId);
        if (session == null) {
            throw new APIException("InterviewSession not found: " + sessionId);
        }

        String prompt = buildPrompt(transcript);

        String jsonResponse = openAiService.askForJson(prompt);
        if (jsonResponse == null || jsonResponse.isBlank()) return;

        JsonNode analysisJson;
        try {
            analysisJson = mapper.readTree(jsonResponse);
        } catch (Exception e) {
            throw new APIException("AI returned invalid JSON");
        }

        InterviewAnalysisByAi analysis = analysisRepo.findByInterviewSession_Id(sessionId);

        if (analysis == null) {
            analysis = new InterviewAnalysisByAi();
            analysis.setInterviewSession(session); // مهم مع @MapsId
        }

// ===== finalScore =====
        int finalScore = analysisJson.get("finalScore").asInt();
        analysis.setFinalScore(finalScore);

// ===== strengths =====
        String strengths = "";
        if (analysisJson.has("strengths") && analysisJson.get("strengths").isArray()) {
            strengths = StreamSupport
                    .stream(analysisJson.get("strengths").spliterator(), false)
                    .map(JsonNode::asText)
                    .collect(Collectors.joining(", "));
        }
        analysis.setStrengths(strengths);

// ===== weaknesses =====
        String weaknesses = "";
        if (analysisJson.has("weaknesses") && analysisJson.get("weaknesses").isArray()) {
            weaknesses = StreamSupport
                    .stream(analysisJson.get("weaknesses").spliterator(), false)
                    .map(JsonNode::asText)
                    .collect(Collectors.joining(", "));
        }
        analysis.setWeaknesses(weaknesses);

// ===== save =====
        analysisRepo.save(analysis);
    }

    // ================== PROMPT ==================

    private String buildPrompt(String transcript) {
        return """
You are a senior technical interview evaluator for a system called "Sijal".

You are given a RAW, noisy transcript generated by a voice AI.
The transcript may contain:
- "AI:" and "User:" prefixes
- repeated or cut sentences
- unclear or short answers
- irrelevant chatter

IMPORTANT:
Evaluate ONLY the USER answers.
Ignore AI messages except for understanding the question context.

If the user's answers are short or unclear:
- Do NOT assume incompetence
- Penalize moderately, not harshly

RETURN ONLY valid JSON.
NO markdown, NO explanations, NO extra text.

JSON FORMAT (MUST MATCH EXACTLY):

{
  "finalScore": number,
  "strengths": [string, string, string],
  "weaknesses": [string, string, string]
}

STRICT RULES:
- finalScore must be an INTEGER between 0 and 100
- strengths must contain EXACTLY 3 items
- weaknesses must contain EXACTLY 3 items
- Each item must be 4–14 words
- Do NOT repeat the same idea twice

SCORING LOGIC:
- 0–20  : User mostly unresponsive or completely irrelevant
- 21–40 : Very limited answers, minimal clarity
- 41–60 : Some relevance, lacks depth or structure
- 61–80 : Clear answers with reasonable understanding
- 81–100: Excellent clarity, confidence, and technical depth

GUIDELINES:
- If the user tries to answer but lacks detail → score 35–55
- If the user shows intent but poor articulation → mention communication weakness
- Strengths should include effort, engagement, or relevance if applicable
- Weaknesses should be specific and constructive

Transcript:
%s
""".formatted(transcript);
    }
}