package org.example.sijalsystem.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.example.sijalsystem.API.APIException;
import org.example.sijalsystem.DTO.OUT.InterviewAnalysisDTOout;
import org.example.sijalsystem.Model.InterviewSession;
import org.example.sijalsystem.Model.InterviewAnalysisByAi;
import org.example.sijalsystem.Repository.InterviewSessionRepository;
import org.example.sijalsystem.Repository.InterviewAnalysisByAiRepository;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

@Service
@RequiredArgsConstructor
public class InterviewAnalysisByAiService {

    private final InterviewSessionRepository sessionRepo;
    private final InterviewAnalysisByAiRepository analysisRepo;
    private final OpenAiService openAiService;

    private final ObjectMapper mapper = new ObjectMapper();

    public List<InterviewAnalysisDTOout> getAllAnalysesForCustomer(Integer customerId) {

        List<InterviewAnalysisByAi> analyses = analysisRepo.findByInterviewSession_Customer_Id(customerId);
        if (analyses.isEmpty()){
            throw new APIException("No analysis for you sessions");
        }
        List<InterviewAnalysisDTOout> dtoList = new ArrayList<>();

        for (InterviewAnalysisByAi a : analyses) {
            dtoList.add(toDto(a));
        }
        return dtoList;
    }

    public InterviewAnalysisDTOout getAnalysisForSession(Integer customerId, Integer sessionId) {

        boolean owned = sessionRepo.existsByIdAndCustomer_Id(sessionId, customerId);
        if (!owned) throw new APIException("not found sessions");

        InterviewAnalysisByAi analysis = analysisRepo.findByInterviewSession_Id(sessionId);
        if (analysis==null){
            throw new APIException("No analysis for this session");
        }

        return toDto(analysis);
    }

    private InterviewAnalysisDTOout toDto(InterviewAnalysisByAi a) {
        return new InterviewAnalysisDTOout(
                a.getFinalScore(),
                a.getStrengths(),
                a.getWeaknesses()
        );
    }


    @Transactional
    public void analyzeAndSave(Integer sessionId, String transcript) {

        InterviewSession session = sessionRepo.findInterviewSessionById(sessionId);
        if (session == null) {
            throw new APIException("InterviewSession not found: " + sessionId);
        }

        String prompt = buildPrompt(transcript);

        String jsonResponse = openAiService.askForJson(prompt);
        if (jsonResponse == null || jsonResponse.isBlank()) return;

        JsonNode analysisJson;
        try {
            analysisJson = mapper.readTree(jsonResponse);
        } catch (Exception e) {
            throw new APIException("AI returned invalid JSON");
        }

        InterviewAnalysisByAi analysis = analysisRepo.findByInterviewSession_Id(sessionId);

        if (analysis == null) {
            analysis = new InterviewAnalysisByAi();
            analysis.setInterviewSession(session);
        }

        int finalScore = analysisJson.get("finalScore").asInt();
        analysis.setFinalScore(finalScore);


        String strengths = "";
        if (analysisJson.has("strengths") && analysisJson.get("strengths").isArray()) {
            strengths = StreamSupport
                    .stream(analysisJson.get("strengths").spliterator(), false)
                    .map(JsonNode::asText)
                    .collect(Collectors.joining(", "));
        }
        analysis.setStrengths(strengths);


        String weaknesses = "";
        if (analysisJson.has("weaknesses") && analysisJson.get("weaknesses").isArray()) {
            weaknesses = StreamSupport
                    .stream(analysisJson.get("weaknesses").spliterator(), false)
                    .map(JsonNode::asText)
                    .collect(Collectors.joining(", "));
        }
        analysis.setWeaknesses(weaknesses);

        session.setStatus("COMPLETED");
        analysisRepo.save(analysis);
    }


    private String buildPrompt(String transcript) {
        return """

You are a senior technical interview evaluator for a system called "Sijal".

You are given:
- Interview questions generated by AI
- A RAW, noisy transcript of the user's answers
- (Optional) A job description

The transcript may contain:
- "AI:" and "User:" prefixes
- unclear, repeated, or incomplete answers
- hesitation sounds like "uh", "um", pauses, or silence

IMPORTANT:
- Evaluate ONLY the USER answers
- Use AI questions ONLY for context
- Do NOT assume incompetence for short or unclear answers
- Penalize moderately

PRIMARY GOAL:
Evaluate whether the user is SUITABLE for the job role based on:
- Relevance of answers to the questions
- Alignment with the job description (if provided)
- Technical understanding shown in answers
- Communication clarity and hesitation patterns

JOB FIT DECISION RULES:
- If the user's answers clearly match the job requirements → user is FIT
- If answers are related but shallow → user is PARTIALLY FIT
- If answers do NOT align with the role → user is NOT FIT

HOW TO REFLECT JOB FIT:
- If FIT or PARTIALLY FIT → mention suitability in STRENGTHS
- If NOT FIT → mention lack of suitability in WEAKNESSES
- If NOT FIT → suggest ONE alternative technical path or role in WEAKNESSES

HESITATION ANALYSIS:
- Detect hesitation such as "uh", silence, or unclear phrasing
- Treat hesitation as a communication weakness, not a knowledge failure

RETURN ONLY valid JSON.
NO markdown.
NO explanations.
NO extra text.

JSON FORMAT (MUST MATCH EXACTLY):

{
  "finalScore": number,
  "strengths": [string, string, string],
  "weaknesses": [string, string, string]
}

STRICT RULES:
- finalScore must be an INTEGER between 0 and 100
- strengths must contain EXACTLY 3 items
- weaknesses must contain EXACTLY 3 items
- Each item must be 4–14 words
- Do NOT repeat the same idea twice

SCORING LOGIC:
- 0–20  : Mostly unresponsive or irrelevant
- 21–40 : Very limited relevance
- 41–60 : Some relevance, lacks depth
- 61–80 : Clear understanding, reasonable alignment
- 81–100: Strong technical and role alignment

Transcript:
%s
""".formatted(transcript);
    }
}