package org.example.sijalsystem.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.example.sijalsystem.API.APIException;
import org.example.sijalsystem.DTO.OUT.InterviewAnalysisDTOout;
import org.example.sijalsystem.Model.InterviewSession;
import org.example.sijalsystem.Model.InterviewAnalysisByAi;
import org.example.sijalsystem.Repository.InterviewSessionRepository;
import org.example.sijalsystem.Repository.InterviewAnalysisByAiRepository;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

@Service
@RequiredArgsConstructor
public class InterviewAnalysisByAiService {

    private final InterviewSessionRepository sessionRepo;
    private final InterviewAnalysisByAiRepository analysisRepo;
    private final OpenAiService openAiService;

    private final ObjectMapper mapper = new ObjectMapper();

    public List<InterviewAnalysisDTOout> getAllAnalysesForCustomer(Integer customerId) {

        List<InterviewAnalysisByAi> analyses = analysisRepo.findByInterviewSession_Customer_Id(customerId);
        if (analyses.isEmpty()){
            throw new APIException("No analysis for you sessions");
        }
        List<InterviewAnalysisDTOout> dtoList = new ArrayList<>();

        for (InterviewAnalysisByAi a : analyses) {
            dtoList.add(toDto(a));
        }
        return dtoList;
    }

    public InterviewAnalysisDTOout getAnalysisForSession(Integer customerId, Integer sessionId) {

        boolean owned = sessionRepo.existsByIdAndCustomer_Id(sessionId, customerId);
        if (!owned) throw new APIException("SESSION_NOT_FOUND");

        InterviewAnalysisByAi analysis = analysisRepo.findByInterviewSession_Id(sessionId);
        if (analysis==null){
            throw new APIException("No analysis for this session");
        }

        return toDto(analysis);
    }

    private InterviewAnalysisDTOout toDto(InterviewAnalysisByAi a) {
        return new InterviewAnalysisDTOout(
                a.getFinalScore(),
                a.getStrengths(),
                a.getWeaknesses()
        );
    }


    @Transactional
    public void analyzeAndSave(Integer sessionId, String transcript) {

        InterviewSession session = sessionRepo.findInterviewSessionById(sessionId);
        if (session == null) {
            throw new APIException("InterviewSession not found: " + sessionId);
        }

        String prompt = buildPrompt(transcript);

        String jsonResponse = openAiService.askForJson(prompt);
        if (jsonResponse == null || jsonResponse.isBlank()) return;

        JsonNode analysisJson;
        try {
            analysisJson = mapper.readTree(jsonResponse);
        } catch (Exception e) {
            throw new APIException("AI returned invalid JSON");
        }

        InterviewAnalysisByAi analysis = analysisRepo.findByInterviewSession_Id(sessionId);

        if (analysis == null) {
            analysis = new InterviewAnalysisByAi();
            analysis.setInterviewSession(session);
        }

        int finalScore = analysisJson.get("finalScore").asInt();
        analysis.setFinalScore(finalScore);


        String strengths = "";
        if (analysisJson.has("strengths") && analysisJson.get("strengths").isArray()) {
            strengths = StreamSupport
                    .stream(analysisJson.get("strengths").spliterator(), false)
                    .map(JsonNode::asText)
                    .collect(Collectors.joining(", "));
        }
        analysis.setStrengths(strengths);


        String weaknesses = "";
        if (analysisJson.has("weaknesses") && analysisJson.get("weaknesses").isArray()) {
            weaknesses = StreamSupport
                    .stream(analysisJson.get("weaknesses").spliterator(), false)
                    .map(JsonNode::asText)
                    .collect(Collectors.joining(", "));
        }
        analysis.setWeaknesses(weaknesses);

        session.setStatus("COMPLETED");
        analysisRepo.save(analysis);
    }


    private String buildPrompt(String transcript) {
        return """
                You are a senior technical interview evaluator for a system called "Sijal".
                
                  You are given a RAW, noisy transcript generated by a voice AI.
                  The transcript may contain:
                  - "AI:" and "User:" prefixes
                  - repeated or cut sentences
                  - unclear or short answers
                  - filler or hesitation sounds such as: "uh", "um", "er", "ah", "aa"
                
                  IMPORTANT:
                  Evaluate ONLY the USER answers.
                  Ignore AI messages except for understanding the QUESTION being asked.
                
                  EVALUATION SCOPE:
                  You must evaluate ALL of the following:
                  1) Whether the user's answer is RELEVANT to the question
                  2) Whether the answer is TECHNICALLY CORRECT at a basic level
                  3) Whether the answer shows UNDERSTANDING or just guessing
                  4) Clarity of explanation and structure
                  5) Hesitation, pauses, or filler words (communication quality)
                
                  HESITATION RULES:
                  - Occasional filler words are normal and should NOT be penalized heavily.
                  - Frequent hesitation or long pauses indicate low confidence or weak understanding.
                  - If the answer is technically correct but hesitant → score moderately.
                  - If the answer is confident but incorrect → penalize correctness.
                
                  DO NOT assume incompetence if the answer is short.
                  Judge based on correctness, relevance, and intent.
                
                  RETURN ONLY valid JSON.
                  NO markdown.
                  NO explanations.
                  NO extra text.
                
                  JSON FORMAT (MUST MATCH EXACTLY):
                
                  {
                    "finalScore": number,
                    "strengths": [string, string, string],
                    "weaknesses": [string, string, string]
                  }
                
                  STRICT RULES:
                  - finalScore must be an INTEGER between 0 and 100
                  - strengths MUST contain EXACTLY 3 items
                  - weaknesses MUST contain EXACTLY 3 items
                  - Each item must be between 4 and 14 words
                  - Do NOT repeat the same idea in different wording
                
                  SCORING GUIDE:
                  - 0–20  : Answers mostly incorrect, irrelevant, or unresponsive
                  - 21–40 : Minimal understanding, frequent incorrect or unclear answers
                  - 41–60 : Some correct ideas but lacks clarity or depth
                  - 61–80 : Mostly correct answers with reasonable understanding
                  - 81–100: Correct, relevant, and clearly explained answers
                
                  GUIDELINES:
                  - Correct but shallow answers → mid score
                  - Incorrect answers even if confident → lower score
                  - Partial correctness → mention in weaknesses
                  - Strengths may include correctness, relevance, or effort
                
                  Transcript:
                  %s
""".formatted(transcript);
    }
}